app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_persona:
    resource: "@AppBundle/Resources/config/routing/persona.yml"
    prefix:   /persona

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
